from actions import*
from attributes import Element, Reactions

RaiFish = {"list": [Skill(0, 0),
                    Swap(2, 0.62),
                    Skill(2, 0.85, infusion=Element.ELECTRO),
                    Reaction(2, 1.1, Reactions.ELECTROSWIRL),
                    Reaction(2, 1.9, Reactions.ELECTROSWIRL),
                    Swap(1, 1.9),
                    Skill(1, 2.13),
                    Reaction(1, 2.42, Reactions.OVERLOAD),
                    Burst(1, 2.85),
                    Swap(3, 3.72),
                    Normal(3, 3.95, 2),
                    Charged(3, 4.5),
                    Reaction(0, 4.47, Reactions.OVERLOAD),
                    Burst(3, 4.58),
                    Reaction(3, 4.73, Reactions.OVERLOAD),
                    Swap(2, 5),
                    Burst(2, 5.23, infusion=Element.PYRO),
                    Reaction(2, 6.62, Reactions.ELECTROSWIRL),
                    Swap(0, 6.83),
                    Burst(0, 7.07),
                    Reaction(2, 7.7, Reactions.ELECTROSWIRL),
                    Reaction(2, 7.7, Reactions.OVERLOAD),
                    Normal(0, 8.93, 3),
                    Reaction(2, 9.65, Reactions.ELECTROSWIRL),
                    Reaction(2, 9.65, Reactions.OVERLOAD),
                    Normal(0, 11.08, 3),
                    Reaction(2, 11.6, Reactions.ELECTROSWIRL),
                    Reaction(2, 11.6, Reactions.OVERLOAD),
                    Normal(0, 13.23, 3),
                    Reaction(2, 13.55, Reactions.ELECTROSWIRL),
                    Reaction(2, 13.55, Reactions.OVERLOAD),
                    Swap(3, 15.37),
                    Reaction(2, 15.5, Reactions.ELECTROSWIRL),
                    Reaction(2, 15.5, Reactions.OVERLOAD),
                    Charged(3, 15.5),
                    Normal(3, 15.4, 1),
                    Skill(3, 15.6),
                    Swap(2, 16.6),
                    Skill(2, 16.83, infusion=Element.PYRO),
                    Reaction(2, 17.08, Reactions.ELECTROSWIRL),
                    Reaction(2, 17.87, Reactions.ELECTROSWIRL),
                    Reaction(2, 17.87, Reactions.OVERLOAD),
                    Normal(3, 18, 3),  # TODO: make this not jank
                    Swap(0, 18.95),
                    Skill(0, 19.18),
                    Normal(0, 20.05, 1),
                    Swap(1, 20.07),
                    Skill(1, 20.3),
                    Reaction(1, 20.58, Reactions.OVERLOAD),
                    Burst(1, 21.02),
                    Reaction(1, 21.65, Reactions.OVERLOAD),
                    Swap(3, 21.88),
                    Normal(3, 22.38, 2),
                    Burst(3, 22.75),
                    Swap(2, 23.15),
                    Skill(2, 23.4, infusion=Element.PYRO),
                    Reaction(2, 23.65, reaction=Reactions.ELECTROSWIRL),
                    Reaction(2, 24.43, reaction=Reactions.ELECTROSWIRL),
                    Reaction(2, 24.435, reaction=Reactions.OVERLOAD),
                    Burst(2, 24.45, infusion=Element.PYRO),
                    Reaction(2, 25.82, reaction=Reactions.ELECTROSWIRL),
                    Swap(0, 26.05),
                    Burst(0, 26.28),
                    Reaction(2, 26.92, reaction=Reactions.OVERLOAD),
                    Reaction(2, 26.92, reaction=Reactions.ELECTROSWIRL),
                    Normal(0, 28.15, 3),
                    Reaction(2, 28.87, reaction=Reactions.OVERLOAD),
                    Reaction(2, 28.87, reaction=Reactions.ELECTROSWIRL),
                    Normal(0, 30.3, 3),
                    Reaction(2, 30.82, reaction=Reactions.OVERLOAD),
                    Reaction(2, 30.82, reaction=Reactions.ELECTROSWIRL),
                    Normal(0, 32.45, 3),
                    Reaction(2, 32.77, reaction=Reactions.OVERLOAD),
                    Reaction(2, 32.77, reaction=Reactions.ELECTROSWIRL),
                    Swap(2, 34.15),
                    Reaction(2, 34.72, reaction=Reactions.OVERLOAD),
                    Reaction(2, 34.72, reaction=Reactions.ELECTROSWIRL),
                    Skill(2, 34.82, infusion=Element.PYRO),
                    Reaction(2, 35.87, reaction=Reactions.PYROSWIRL),
                    Swap(0, 35.87)],
           "length": 36}

Sukokomon = {"list" : [],
             "length": 25}