from character.bennett import*
from character.kazuha import*
from character.raiden import*
from character.fischl import*
from character.kokomi import*
from character.xiangling import*
from character.sucrose import*
from character.xingqiu import*
from character.beidou import*
from character.collei import*
from character.hutao import*
from character.yelan import*